-- Migration: Config Builder foundations
-- Created: 2026-02-19

CREATE TABLE IF NOT EXISTS config_templates (
  id TEXT PRIMARY KEY,
  workspace_id TEXT REFERENCES workspaces(id) ON DELETE CASCADE,
  created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  goal TEXT NOT NULL,
  category TEXT NOT NULL,
  template_type TEXT DEFAULT 'assistant',
  channels TEXT DEFAULT '[]',
  providers TEXT DEFAULT '[]',
  tags TEXT DEFAULT '[]',
  base_config_json TEXT NOT NULL,
  default_options_json TEXT DEFAULT '{}',
  schema_json TEXT DEFAULT '{}',
  is_official INTEGER DEFAULT 0,
  is_featured INTEGER DEFAULT 1,
  is_active INTEGER DEFAULT 1,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_config_templates_slug_official
ON config_templates(slug)
WHERE workspace_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_config_templates_workspace ON config_templates(workspace_id);
CREATE INDEX IF NOT EXISTS idx_config_templates_goal ON config_templates(goal);
CREATE INDEX IF NOT EXISTS idx_config_templates_official ON config_templates(is_official);

CREATE TABLE IF NOT EXISTS config_setups (
  id TEXT PRIMARY KEY,
  workspace_id TEXT REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  slug TEXT,
  source_mode TEXT NOT NULL,
  template_id TEXT REFERENCES config_templates(id) ON DELETE SET NULL,
  options_json TEXT DEFAULT '{}',
  config_json TEXT NOT NULL,
  summary TEXT,
  is_public INTEGER DEFAULT 0,
  downloads INTEGER DEFAULT 0,
  last_downloaded_at TEXT,
  deleted_at TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_config_setups_workspace ON config_setups(workspace_id);
CREATE INDEX IF NOT EXISTS idx_config_setups_user ON config_setups(user_id);
CREATE INDEX IF NOT EXISTS idx_config_setups_template ON config_setups(template_id);
CREATE INDEX IF NOT EXISTS idx_config_setups_deleted ON config_setups(deleted_at);
CREATE INDEX IF NOT EXISTS idx_config_setups_created ON config_setups(created_at);

CREATE TABLE IF NOT EXISTS config_setup_versions (
  id TEXT PRIMARY KEY,
  setup_id TEXT REFERENCES config_setups(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  config_json TEXT NOT NULL,
  options_json TEXT DEFAULT '{}',
  created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_config_setup_versions_setup ON config_setup_versions(setup_id);
CREATE INDEX IF NOT EXISTS idx_config_setup_versions_created ON config_setup_versions(created_at);

INSERT OR IGNORE INTO config_templates (
  id, workspace_id, created_by_user_id, slug, name, description, goal, category, template_type,
  channels, providers, tags, base_config_json, default_options_json, schema_json, is_official, is_featured, is_active
)
VALUES
(
  'tmpl-openclaw-starter',
  NULL,
  NULL,
  'openclaw-starter',
  'OpenClaw Starter',
  'Starter template for a simple personal assistant.',
  'personal',
  'personal',
  'assistant',
  '["telegram"]',
  '["openai"]',
  '["starter","personal"]',
  '{"version":"1.0.0","agent":{"provider":"openai","model":"gpt-4o","tools":["read","write","edit"],"logging_level":"errors"},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"personal","channels":["telegram"],"provider":"openai","model":"gpt-4o","memory":false}',
  '{"agent":{"provider":"Provider name","model":"Primary model"},"channels":"Configured output channels"}',
  1,
  1,
  1
),
(
  'tmpl-customer-support-rag',
  NULL,
  NULL,
  'customer-support-rag',
  'Customer Support (RAG-ready)',
  'Support-focused baseline with memory enabled for support flows.',
  'support',
  'support',
  'assistant',
  '["telegram"]',
  '["openai","anthropic"]',
  '["support","rag"]',
  '{"version":"1.0.0","agent":{"provider":"openai","model":"gpt-4o","memory":{"enabled":true,"backend":"sqlite"},"tools":["read","write","edit"],"logging_level":"errors"},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"support","channels":["telegram"],"provider":"openai","model":"gpt-4o","memory":true}',
  '{"agent.memory.backend":"Storage backend for long-term memory","channels[].token":"Telegram bot token"}',
  1,
  1,
  1
),
(
  'tmpl-developer-box',
  NULL,
  NULL,
  'developer-box',
  'Developer Box',
  'Developer helper with verbose logging and safety flags.',
  'dev',
  'dev',
  'assistant',
  '["telegram"]',
  '["openai"]',
  '["developer","coding"]',
  '{"version":"1.0.0","agent":{"provider":"openai","model":"gpt-4.1","tools":["read","write","edit","exec"],"logging_level":"verbose","safety_flags":["safe_commands"]},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"dev","channels":["telegram"],"provider":"openai","model":"gpt-4.1","memory":false}',
  '{"agent.tools":"Tool list used by this config"}',
  1,
  1,
  1
),
(
  'tmpl-content-creator',
  NULL,
  NULL,
  'content-creator',
  'Content Creator',
  'Template optimized for drafting and social content.',
  'content',
  'content',
  'assistant',
  '["telegram"]',
  '["openai","anthropic"]',
  '["content","marketing"]',
  '{"version":"1.0.0","agent":{"provider":"anthropic","model":"claude-3-5-sonnet","tools":["read","write","edit"],"logging_level":"errors"},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"content","channels":["telegram"],"provider":"anthropic","model":"claude-3-5-sonnet","memory":false}',
  '{"agent.model":"Primary drafting model"}',
  1,
  1,
  1
),
(
  'tmpl-telegram-community-manager',
  NULL,
  NULL,
  'telegram-community-manager',
  'Community Manager (Telegram)',
  'Moderation and community engagement baseline.',
  'community',
  'community',
  'assistant',
  '["telegram"]',
  '["openai","minimax"]',
  '["community","telegram"]',
  '{"version":"1.0.0","agent":{"provider":"openai","model":"gpt-4o","tools":["read","write"],"logging_level":"errors"},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"community","channels":["telegram"],"provider":"openai","model":"gpt-4o","memory":true}',
  '{"channels[].type":"Output channel type"}',
  1,
  1,
  1
),
(
  'tmpl-research-briefing-bot',
  NULL,
  NULL,
  'research-briefing-bot',
  'Research & Briefing Bot',
  'Research-first assistant with optional fallback chain.',
  'research',
  'research',
  'assistant',
  '["telegram"]',
  '["openai","anthropic","minimax"]',
  '["research","briefing"]',
  '{"version":"1.0.0","agent":{"provider":"anthropic","model":"claude-3-7-sonnet","fallback_chain":["gpt-4o"],"tools":["read","write","edit"],"logging_level":"errors"},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"research","channels":["telegram"],"provider":"anthropic","model":"claude-3-7-sonnet","fallbackEnabled":true,"fallbackChain":["gpt-4o"]}',
  '{"agent.fallback_chain":"Ordered fallback model list"}',
  1,
  1,
  1
),
(
  'tmpl-sales-qualifier',
  NULL,
  NULL,
  'sales-qualifier',
  'Sales Qualifier / Lead Intake',
  'Sales intake with Telegram and WhatsApp defaults.',
  'sales',
  'sales',
  'assistant',
  '["telegram","whatsapp"]',
  '["openai","minimax"]',
  '["sales","lead"]',
  '{"version":"1.0.0","agent":{"provider":"openai","model":"gpt-4o","tools":["read","write"],"logging_level":"errors"},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"},{"type":"whatsapp","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"sales","channels":["telegram","whatsapp"],"provider":"openai","model":"gpt-4o","memory":false}',
  '{"channels[].token":"Channel credential token"}',
  1,
  1,
  1
),
(
  'tmpl-founder-exec-assistant',
  NULL,
  NULL,
  'founder-exec-assistant',
  'Founder / Exec Assistant',
  'Personal assistant for prioritization and follow-up.',
  'personal',
  'personal',
  'assistant',
  '["telegram"]',
  '["openai","anthropic"]',
  '["assistant","executive"]',
  '{"version":"1.0.0","agent":{"provider":"anthropic","model":"claude-3-5-sonnet","tools":["read","write","edit"],"logging_level":"errors"},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"personal","channels":["telegram"],"provider":"anthropic","model":"claude-3-5-sonnet","memory":true}',
  '{"agent.logging_level":"none|errors|verbose"}',
  1,
  1,
  1
),
(
  'tmpl-local-ollama-low-cost',
  NULL,
  NULL,
  'local-ollama-low-cost',
  'Low Cost / Local (Ollama)',
  'Local-only mode without cloud API billing.',
  'personal',
  'personal',
  'assistant',
  '["telegram"]',
  '["ollama"]',
  '["ollama","local"]',
  '{"version":"1.0.0","agent":{"provider":"ollama","model":"llama3.1","endpoint":"http://127.0.0.1:11434","tools":["read","write","edit"],"logging_level":"errors"},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"personal","channels":["telegram"],"provider":"ollama","model":"llama3.1","memory":false}',
  '{"agent.endpoint":"Ollama HTTP endpoint"}',
  1,
  1,
  1
),
(
  'tmpl-privacy-first-local',
  NULL,
  NULL,
  'privacy-first-local',
  'Privacy-First Local',
  'No cloud provider fallback, local execution only.',
  'personal',
  'personal',
  'assistant',
  '["telegram"]',
  '["ollama"]',
  '["privacy","local"]',
  '{"version":"1.0.0","agent":{"provider":"ollama","model":"qwen2.5","endpoint":"http://127.0.0.1:11434","tools":["read","write","edit"],"logging_level":"errors"},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"personal","channels":["telegram"],"provider":"ollama","model":"qwen2.5","memory":true}',
  '{"agent.provider":"Cloud providers disabled for this template"}',
  1,
  1,
  1
),
(
  'tmpl-ecommerce-helper',
  NULL,
  NULL,
  'ecommerce-helper',
  'E-commerce Helper',
  'Customer support helper for storefront questions.',
  'support',
  'support',
  'assistant',
  '["whatsapp"]',
  '["openai","anthropic"]',
  '["ecommerce","support"]',
  '{"version":"1.0.0","agent":{"provider":"openai","model":"gpt-4o","tools":["read","write"],"logging_level":"errors"},"channels":[{"type":"whatsapp","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"support","channels":["whatsapp"],"provider":"openai","model":"gpt-4o","memory":true}',
  '{"channels[].token":"WhatsApp token"}',
  1,
  1,
  1
),
(
  'tmpl-multi-model-fallback',
  NULL,
  NULL,
  'multi-model-fallback',
  'Multi-Model Fallback',
  'Primary + fallback chain baseline for reliability.',
  'support',
  'support',
  'assistant',
  '["telegram"]',
  '["openai","anthropic"]',
  '["fallback","resilience"]',
  '{"version":"1.0.0","agent":{"provider":"openai","model":"gpt-4o","fallback_chain":["claude-3-5-sonnet","gpt-3.5-turbo"],"tools":["read","write","edit"],"logging_level":"errors"},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"support","channels":["telegram"],"provider":"openai","model":"gpt-4o","fallbackEnabled":true,"fallbackChain":["claude-3-5-sonnet","gpt-3.5-turbo"]}',
  '{"agent.fallback_chain":"List of fallback model slugs in retry order"}',
  1,
  1,
  1
),
(
  'tmpl-claude-assistant',
  NULL,
  NULL,
  'claude-assistant',
  'Claude Assistant',
  'Anthropic-first assistant baseline.',
  'support',
  'support',
  'assistant',
  '["telegram"]',
  '["anthropic"]',
  '["anthropic","assistant"]',
  '{"version":"1.0.0","agent":{"provider":"anthropic","model":"claude-3-7-sonnet","tools":["read","write","edit"],"logging_level":"errors"},"channels":[{"type":"telegram","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"support","channels":["telegram"],"provider":"anthropic","model":"claude-3-7-sonnet","memory":false}',
  '{"agent.model":"Anthropic model slug"}',
  1,
  1,
  1
),
(
  'tmpl-whatsapp-business-bot',
  NULL,
  NULL,
  'whatsapp-business-bot',
  'WhatsApp Business Bot',
  'WhatsApp-focused sales and intake workflow.',
  'sales',
  'sales',
  'assistant',
  '["whatsapp"]',
  '["openai"]',
  '["whatsapp","sales"]',
  '{"version":"1.0.0","agent":{"provider":"openai","model":"gpt-4o","tools":["read","write"],"logging_level":"errors"},"channels":[{"type":"whatsapp","enabled":true,"token":"YOUR_TOKEN"}]}',
  '{"goal":"sales","channels":["whatsapp"],"provider":"openai","model":"gpt-4o","memory":false}',
  '{"channels[].token":"WhatsApp Business credential token"}',
  1,
  1,
  1
);
